<?php

namespace DoctrineProxies\__CG__\Entity;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Candidato extends \Entity\Candidato implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setNome($nome)
    {
        $this->__load();
        return parent::setNome($nome);
    }

    public function getNome()
    {
        $this->__load();
        return parent::getNome();
    }

    public function setNomeUrna($nomeUrna)
    {
        $this->__load();
        return parent::setNomeUrna($nomeUrna);
    }

    public function getNomeUrna()
    {
        $this->__load();
        return parent::getNomeUrna();
    }

    public function setCandidatura($candidatura)
    {
        $this->__load();
        return parent::setCandidatura($candidatura);
    }

    public function getCandidatura()
    {
        $this->__load();
        return parent::getCandidatura();
    }

    public function setNumero($numero)
    {
        $this->__load();
        return parent::setNumero($numero);
    }

    public function getNumero()
    {
        $this->__load();
        return parent::getNumero();
    }

    public function setSituacao($situacao)
    {
        $this->__load();
        return parent::setSituacao($situacao);
    }

    public function getSituacao()
    {
        $this->__load();
        return parent::getSituacao();
    }

    public function setCargoAtual($cargoAtual)
    {
        $this->__load();
        return parent::setCargoAtual($cargoAtual);
    }

    public function getCargoAtual()
    {
        $this->__load();
        return parent::getCargoAtual();
    }

    public function setSexo($sexo)
    {
        $this->__load();
        return parent::setSexo($sexo);
    }

    public function getSexo()
    {
        $this->__load();
        return parent::getSexo();
    }

    public function setDtNascimento($dtNascimento)
    {
        $this->__load();
        return parent::setDtNascimento($dtNascimento);
    }

    public function getDtNascimento()
    {
        $this->__load();
        return parent::getDtNascimento();
    }

    public function setColigacao($coligacao)
    {
        $this->__load();
        return parent::setColigacao($coligacao);
    }

    public function getColigacao()
    {
        $this->__load();
        return parent::getColigacao();
    }

    public function setCidade($cidade)
    {
        $this->__load();
        return parent::setCidade($cidade);
    }

    public function getCidade()
    {
        $this->__load();
        return parent::getCidade();
    }

    public function setUf($uf)
    {
        $this->__load();
        return parent::setUf($uf);
    }

    public function getUf()
    {
        $this->__load();
        return parent::getUf();
    }

    public function setPartido(\Entity\Partido $partido = NULL)
    {
        $this->__load();
        return parent::setPartido($partido);
    }

    public function getPartido()
    {
        $this->__load();
        return parent::getPartido();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'nome', 'nomeUrna', 'candidatura', 'numero', 'situacao', 'cargoAtual', 'sexo', 'dtNascimento', 'coligacao', 'cidade', 'uf', 'partido');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}